// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Stat ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Stat ) UnmarshalJSON([]byte) error { return nil }
func ( Stat ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Stat ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Stat *Stat
