// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  service

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Behavior ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Behavior ) UnmarshalJSON([]byte) error { return nil }
func ( Behavior ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Behavior ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Behavior *Behavior
