// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  repository

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( CSATRepository ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CSATRepository ) UnmarshalJSON([]byte) error { return nil }
func ( CSATRepository ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CSATRepository ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CSATRepository *CSATRepository
