// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( SubscriptionRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SubscriptionRequest ) UnmarshalJSON([]byte) error { return nil }
func ( SubscriptionRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SubscriptionRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SubscriptionRequest *SubscriptionRequest
