// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  service

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Service ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Service ) UnmarshalJSON([]byte) error { return nil }
func ( Service ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Service ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Service *Service
