// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Author ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Author ) UnmarshalJSON([]byte) error { return nil }
func ( Author ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Author ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Author *Author
