// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Subscription ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Subscription ) UnmarshalJSON([]byte) error { return nil }
func ( Subscription ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Subscription ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Subscription *Subscription
