// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( TipRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* TipRequest ) UnmarshalJSON([]byte) error { return nil }
func ( TipRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* TipRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TipRequest *TipRequest
