// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  postgresql

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( ContentRepository ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ContentRepository ) UnmarshalJSON([]byte) error { return nil }
func ( ContentRepository ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ContentRepository ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ContentRepository *ContentRepository
