// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Question ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Question ) UnmarshalJSON([]byte) error { return nil }
func ( Question ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Question ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Question *Question
