// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2419208eDecodeGithubComGoParkMailRu20242TeamOnPatreonInternalAuthorPkgModels(in *jlexer.Lexer, out *Graphic) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "valueX":
			if in.IsNull() {
				in.Skip()
				out.PointsX = nil
			} else {
				in.Delim('[')
				if out.PointsX == nil {
					if !in.IsDelim(']') {
						out.PointsX = make([]int, 0, 8)
					} else {
						out.PointsX = []int{}
					}
				} else {
					out.PointsX = (out.PointsX)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int
					v1 = int(in.Int())
					out.PointsX = append(out.PointsX, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "valueY":
			if in.IsNull() {
				in.Skip()
				out.PointsY = nil
			} else {
				in.Delim('[')
				if out.PointsY == nil {
					if !in.IsDelim(']') {
						out.PointsY = make([]int, 0, 8)
					} else {
						out.PointsY = []int{}
					}
				} else {
					out.PointsY = (out.PointsY)[:0]
				}
				for !in.IsDelim(']') {
					var v2 int
					v2 = int(in.Int())
					out.PointsY = append(out.PointsY, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2419208eEncodeGithubComGoParkMailRu20242TeamOnPatreonInternalAuthorPkgModels(out *jwriter.Writer, in Graphic) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"valueX\":"
		out.RawString(prefix[1:])
		if in.PointsX == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.PointsX {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v4))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"valueY\":"
		out.RawString(prefix)
		if in.PointsY == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.PointsY {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Graphic) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2419208eEncodeGithubComGoParkMailRu20242TeamOnPatreonInternalAuthorPkgModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Graphic) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2419208eEncodeGithubComGoParkMailRu20242TeamOnPatreonInternalAuthorPkgModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Graphic) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2419208eDecodeGithubComGoParkMailRu20242TeamOnPatreonInternalAuthorPkgModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Graphic) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2419208eDecodeGithubComGoParkMailRu20242TeamOnPatreonInternalAuthorPkgModels(l, v)
}
