// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"
)

func main() {
  g := gen.NewGenerator("mock_content_service_easyjson_easyjson.go")
  g.SetPkg("mock_interfaces", "github.com/go-park-mail-ru/2024_2_TeamOn_Patreon/tests/content/mocks/mock_interfaces")
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
