// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\HYPERPC\GolandProjects\2024_2_TeamOn_Patreon\internal\content\service\interfaces\content_repository.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2024_2_TeamOn_Patreon/internal/content/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockContentRepository is a mock of ContentRepository interface.
type MockContentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContentRepositoryMockRecorder
}

// MockContentRepositoryMockRecorder is the mock recorder for MockContentRepository.
type MockContentRepositoryMockRecorder struct {
	mock *MockContentRepository
}

// NewMockContentRepository creates a new mock instance.
func NewMockContentRepository(ctrl *gomock.Controller) *MockContentRepository {
	mock := &MockContentRepository{ctrl: ctrl}
	mock.recorder = &MockContentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentRepository) EXPECT() *MockContentRepositoryMockRecorder {
	return m.recorder
}

// CheckCustomLayer mocks base method.
func (m *MockContentRepository) CheckCustomLayer(ctx context.Context, authorID string, layer int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCustomLayer", ctx, authorID, layer)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCustomLayer indicates an expected call of CheckCustomLayer.
func (mr *MockContentRepositoryMockRecorder) CheckCustomLayer(ctx, authorID, layer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCustomLayer", reflect.TypeOf((*MockContentRepository)(nil).CheckCustomLayer), ctx, authorID, layer)
}

// DeleteLikePost mocks base method.
func (m *MockContentRepository) DeleteLikePost(ctx context.Context, userID, postID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLikePost", ctx, userID, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLikePost indicates an expected call of DeleteLikePost.
func (mr *MockContentRepositoryMockRecorder) DeleteLikePost(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLikePost", reflect.TypeOf((*MockContentRepository)(nil).DeleteLikePost), ctx, userID, postID)
}

// DeletePost mocks base method.
func (m *MockContentRepository) DeletePost(ctx context.Context, postID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", ctx, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockContentRepositoryMockRecorder) DeletePost(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockContentRepository)(nil).DeletePost), ctx, postID)
}

// GetAuthorOfPost mocks base method.
func (m *MockContentRepository) GetAuthorOfPost(ctx context.Context, postID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorOfPost", ctx, postID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorOfPost indicates an expected call of GetAuthorOfPost.
func (mr *MockContentRepositoryMockRecorder) GetAuthorOfPost(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorOfPost", reflect.TypeOf((*MockContentRepository)(nil).GetAuthorOfPost), ctx, postID)
}

// GetAuthorPostsForAnon mocks base method.
func (m *MockContentRepository) GetAuthorPostsForAnon(ctx context.Context, authorID string, offset, limit int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorPostsForAnon", ctx, authorID, offset, limit)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorPostsForAnon indicates an expected call of GetAuthorPostsForAnon.
func (mr *MockContentRepositoryMockRecorder) GetAuthorPostsForAnon(ctx, authorID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorPostsForAnon", reflect.TypeOf((*MockContentRepository)(nil).GetAuthorPostsForAnon), ctx, authorID, offset, limit)
}

// GetAuthorPostsForLayer mocks base method.
func (m *MockContentRepository) GetAuthorPostsForLayer(ctx context.Context, layer int, authorID string, offset, limit int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorPostsForLayer", ctx, layer, authorID, offset, limit)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorPostsForLayer indicates an expected call of GetAuthorPostsForLayer.
func (mr *MockContentRepositoryMockRecorder) GetAuthorPostsForLayer(ctx, layer, authorID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorPostsForLayer", reflect.TypeOf((*MockContentRepository)(nil).GetAuthorPostsForLayer), ctx, layer, authorID, offset, limit)
}

// GetAuthorPostsForMe mocks base method.
func (m *MockContentRepository) GetAuthorPostsForMe(ctx context.Context, authorID string, offset, limit int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorPostsForMe", ctx, authorID, offset, limit)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorPostsForMe indicates an expected call of GetAuthorPostsForMe.
func (mr *MockContentRepositoryMockRecorder) GetAuthorPostsForMe(ctx, authorID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorPostsForMe", reflect.TypeOf((*MockContentRepository)(nil).GetAuthorPostsForMe), ctx, authorID, offset, limit)
}

// GetContentsByPost mocks base method.
func (m *MockContentRepository) GetContentsByPost(ctx context.Context, postID string) ([]*models.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContentsByPost", ctx, postID)
	ret0, _ := ret[0].([]*models.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContentsByPost indicates an expected call of GetContentsByPost.
func (mr *MockContentRepositoryMockRecorder) GetContentsByPost(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContentsByPost", reflect.TypeOf((*MockContentRepository)(nil).GetContentsByPost), ctx, postID)
}

// GetIsLikedForPosts mocks base method.
func (m *MockContentRepository) GetIsLikedForPosts(ctx context.Context, UserID string, posts []*models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIsLikedForPosts", ctx, UserID, posts)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetIsLikedForPosts indicates an expected call of GetIsLikedForPosts.
func (mr *MockContentRepositoryMockRecorder) GetIsLikedForPosts(ctx, UserID, posts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIsLikedForPosts", reflect.TypeOf((*MockContentRepository)(nil).GetIsLikedForPosts), ctx, UserID, posts)
}

// GetPopularPosts mocks base method.
func (m *MockContentRepository) GetPopularPosts(ctx context.Context, offset, limits int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularPosts", ctx, offset, limits)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularPosts indicates an expected call of GetPopularPosts.
func (mr *MockContentRepositoryMockRecorder) GetPopularPosts(ctx, offset, limits interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularPosts", reflect.TypeOf((*MockContentRepository)(nil).GetPopularPosts), ctx, offset, limits)
}

// GetPopularPostsForUser mocks base method.
func (m *MockContentRepository) GetPopularPostsForUser(ctx context.Context, userID string, offset, limits int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularPostsForUser", ctx, userID, offset, limits)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularPostsForUser indicates an expected call of GetPopularPostsForUser.
func (mr *MockContentRepositoryMockRecorder) GetPopularPostsForUser(ctx, userID, offset, limits interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularPostsForUser", reflect.TypeOf((*MockContentRepository)(nil).GetPopularPostsForUser), ctx, userID, offset, limits)
}

// GetPostLayerBuPostID mocks base method.
func (m *MockContentRepository) GetPostLayerByPostID(ctx context.Context, postID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostLayerByPostID", ctx, postID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostLayerBuPostID indicates an expected call of GetPostLayerBuPostID.
func (mr *MockContentRepositoryMockRecorder) GetPostLayerBuPostID(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostLayerByPostID", reflect.TypeOf((*MockContentRepository)(nil).GetPostLayerByPostID), ctx, postID)
}

// GetPostLikeID mocks base method.
func (m *MockContentRepository) GetPostLikeID(ctx context.Context, userID, postID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostLikeID", ctx, userID, postID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostLikeID indicates an expected call of GetPostLikeID.
func (mr *MockContentRepositoryMockRecorder) GetPostLikeID(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostLikeID", reflect.TypeOf((*MockContentRepository)(nil).GetPostLikeID), ctx, userID, postID)
}

// GetPostLikes mocks base method.
func (m *MockContentRepository) GetPostLikes(ctx context.Context, postID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostLikes", ctx, postID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostLikes indicates an expected call of GetPostLikes.
func (mr *MockContentRepositoryMockRecorder) GetPostLikes(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostLikes", reflect.TypeOf((*MockContentRepository)(nil).GetPostLikes), ctx, postID)
}

// GetSubscriptionPostsForUser mocks base method.
func (m *MockContentRepository) GetSubscriptionPostsForUser(ctx context.Context, userID string, offset, limits int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionPostsForUser", ctx, userID, offset, limits)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionPostsForUser indicates an expected call of GetSubscriptionPostsForUser.
func (mr *MockContentRepositoryMockRecorder) GetSubscriptionPostsForUser(ctx, userID, offset, limits interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionPostsForUser", reflect.TypeOf((*MockContentRepository)(nil).GetSubscriptionPostsForUser), ctx, userID, offset, limits)
}

// GetUserLayerOfAuthor mocks base method.
func (m *MockContentRepository) GetUserLayerOfAuthor(ctx context.Context, userID, authorID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserLayerOfAuthor", ctx, userID, authorID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserLayerOfAuthor indicates an expected call of GetUserLayerOfAuthor.
func (mr *MockContentRepositoryMockRecorder) GetUserLayerOfAuthor(ctx, userID, authorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserLayerOfAuthor", reflect.TypeOf((*MockContentRepository)(nil).GetUserLayerOfAuthor), ctx, userID, authorID)
}

// GetUserRole mocks base method.
func (m *MockContentRepository) GetUserRole(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRole", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockContentRepositoryMockRecorder) GetUserRole(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRole", reflect.TypeOf((*MockContentRepository)(nil).GetUserRole), ctx, userID)
}

// InsertLikePost mocks base method.
func (m *MockContentRepository) InsertLikePost(ctx context.Context, userID, postID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLikePost", ctx, userID, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertLikePost indicates an expected call of InsertLikePost.
func (mr *MockContentRepositoryMockRecorder) InsertLikePost(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLikePost", reflect.TypeOf((*MockContentRepository)(nil).InsertLikePost), ctx, userID, postID)
}

// InsertPost mocks base method.
func (m *MockContentRepository) InsertPost(ctx context.Context, userID, postID, title, content string, layer int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPost", ctx, userID, postID, title, content, layer)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPost indicates an expected call of InsertPost.
func (mr *MockContentRepositoryMockRecorder) InsertPost(ctx, userID, postID, title, content, layer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPost", reflect.TypeOf((*MockContentRepository)(nil).InsertPost), ctx, userID, postID, title, content, layer)
}

// UpdateContentOfPost mocks base method.
func (m *MockContentRepository) UpdateContentOfPost(ctx context.Context, postID, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContentOfPost", ctx, postID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContentOfPost indicates an expected call of UpdateContentOfPost.
func (mr *MockContentRepositoryMockRecorder) UpdateContentOfPost(ctx, postID, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContentOfPost", reflect.TypeOf((*MockContentRepository)(nil).UpdateContentOfPost), ctx, postID, content)
}

// UpdateTitleOfPost mocks base method.
func (m *MockContentRepository) UpdateTitleOfPost(ctx context.Context, postID, title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTitleOfPost", ctx, postID, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTitleOfPost indicates an expected call of UpdateTitleOfPost.
func (mr *MockContentRepositoryMockRecorder) UpdateTitleOfPost(ctx, postID, title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTitleOfPost", reflect.TypeOf((*MockContentRepository)(nil).UpdateTitleOfPost), ctx, postID, title)
}

// MockPostInterface is a mock of PostInterface interface.
type MockPostInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPostInterfaceMockRecorder
}

// MockPostInterfaceMockRecorder is the mock recorder for MockPostInterface.
type MockPostInterfaceMockRecorder struct {
	mock *MockPostInterface
}

// NewMockPostInterface creates a new mock instance.
func NewMockPostInterface(ctrl *gomock.Controller) *MockPostInterface {
	mock := &MockPostInterface{ctrl: ctrl}
	mock.recorder = &MockPostInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostInterface) EXPECT() *MockPostInterfaceMockRecorder {
	return m.recorder
}

// DeletePost mocks base method.
func (m *MockPostInterface) DeletePost(ctx context.Context, postID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", ctx, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockPostInterfaceMockRecorder) DeletePost(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockPostInterface)(nil).DeletePost), ctx, postID)
}

// InsertPost mocks base method.
func (m *MockPostInterface) InsertPost(ctx context.Context, userID, postID, title, content string, layer int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPost", ctx, userID, postID, title, content, layer)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPost indicates an expected call of InsertPost.
func (mr *MockPostInterfaceMockRecorder) InsertPost(ctx, userID, postID, title, content, layer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPost", reflect.TypeOf((*MockPostInterface)(nil).InsertPost), ctx, userID, postID, title, content, layer)
}

// UpdateContentOfPost mocks base method.
func (m *MockPostInterface) UpdateContentOfPost(ctx context.Context, postID, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContentOfPost", ctx, postID, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContentOfPost indicates an expected call of UpdateContentOfPost.
func (mr *MockPostInterfaceMockRecorder) UpdateContentOfPost(ctx, postID, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContentOfPost", reflect.TypeOf((*MockPostInterface)(nil).UpdateContentOfPost), ctx, postID, content)
}

// UpdateTitleOfPost mocks base method.
func (m *MockPostInterface) UpdateTitleOfPost(ctx context.Context, postID, title string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTitleOfPost", ctx, postID, title)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTitleOfPost indicates an expected call of UpdateTitleOfPost.
func (mr *MockPostInterfaceMockRecorder) UpdateTitleOfPost(ctx, postID, title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTitleOfPost", reflect.TypeOf((*MockPostInterface)(nil).UpdateTitleOfPost), ctx, postID, title)
}

// MockFeedInterface is a mock of FeedInterface interface.
type MockFeedInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFeedInterfaceMockRecorder
}

// MockFeedInterfaceMockRecorder is the mock recorder for MockFeedInterface.
type MockFeedInterfaceMockRecorder struct {
	mock *MockFeedInterface
}

// NewMockFeedInterface creates a new mock instance.
func NewMockFeedInterface(ctrl *gomock.Controller) *MockFeedInterface {
	mock := &MockFeedInterface{ctrl: ctrl}
	mock.recorder = &MockFeedInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedInterface) EXPECT() *MockFeedInterfaceMockRecorder {
	return m.recorder
}

// GetAuthorPostsForAnon mocks base method.
func (m *MockFeedInterface) GetAuthorPostsForAnon(ctx context.Context, authorID string, offset, limit int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorPostsForAnon", ctx, authorID, offset, limit)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorPostsForAnon indicates an expected call of GetAuthorPostsForAnon.
func (mr *MockFeedInterfaceMockRecorder) GetAuthorPostsForAnon(ctx, authorID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorPostsForAnon", reflect.TypeOf((*MockFeedInterface)(nil).GetAuthorPostsForAnon), ctx, authorID, offset, limit)
}

// GetAuthorPostsForLayer mocks base method.
func (m *MockFeedInterface) GetAuthorPostsForLayer(ctx context.Context, layer int, authorID string, offset, limit int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorPostsForLayer", ctx, layer, authorID, offset, limit)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorPostsForLayer indicates an expected call of GetAuthorPostsForLayer.
func (mr *MockFeedInterfaceMockRecorder) GetAuthorPostsForLayer(ctx, layer, authorID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorPostsForLayer", reflect.TypeOf((*MockFeedInterface)(nil).GetAuthorPostsForLayer), ctx, layer, authorID, offset, limit)
}

// GetAuthorPostsForMe mocks base method.
func (m *MockFeedInterface) GetAuthorPostsForMe(ctx context.Context, authorID string, offset, limit int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorPostsForMe", ctx, authorID, offset, limit)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorPostsForMe indicates an expected call of GetAuthorPostsForMe.
func (mr *MockFeedInterfaceMockRecorder) GetAuthorPostsForMe(ctx, authorID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorPostsForMe", reflect.TypeOf((*MockFeedInterface)(nil).GetAuthorPostsForMe), ctx, authorID, offset, limit)
}

// GetPopularPosts mocks base method.
func (m *MockFeedInterface) GetPopularPosts(ctx context.Context, offset, limits int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularPosts", ctx, offset, limits)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularPosts indicates an expected call of GetPopularPosts.
func (mr *MockFeedInterfaceMockRecorder) GetPopularPosts(ctx, offset, limits interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularPosts", reflect.TypeOf((*MockFeedInterface)(nil).GetPopularPosts), ctx, offset, limits)
}

// GetPopularPostsForUser mocks base method.
func (m *MockFeedInterface) GetPopularPostsForUser(ctx context.Context, userID string, offset, limits int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularPostsForUser", ctx, userID, offset, limits)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularPostsForUser indicates an expected call of GetPopularPostsForUser.
func (mr *MockFeedInterfaceMockRecorder) GetPopularPostsForUser(ctx, userID, offset, limits interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularPostsForUser", reflect.TypeOf((*MockFeedInterface)(nil).GetPopularPostsForUser), ctx, userID, offset, limits)
}

// GetSubscriptionPostsForUser mocks base method.
func (m *MockFeedInterface) GetSubscriptionPostsForUser(ctx context.Context, userID string, offset, limits int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionPostsForUser", ctx, userID, offset, limits)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionPostsForUser indicates an expected call of GetSubscriptionPostsForUser.
func (mr *MockFeedInterfaceMockRecorder) GetSubscriptionPostsForUser(ctx, userID, offset, limits interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionPostsForUser", reflect.TypeOf((*MockFeedInterface)(nil).GetSubscriptionPostsForUser), ctx, userID, offset, limits)
}

// MockLikePostInterface is a mock of LikePostInterface interface.
type MockLikePostInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLikePostInterfaceMockRecorder
}

// MockLikePostInterfaceMockRecorder is the mock recorder for MockLikePostInterface.
type MockLikePostInterfaceMockRecorder struct {
	mock *MockLikePostInterface
}

// NewMockLikePostInterface creates a new mock instance.
func NewMockLikePostInterface(ctrl *gomock.Controller) *MockLikePostInterface {
	mock := &MockLikePostInterface{ctrl: ctrl}
	mock.recorder = &MockLikePostInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLikePostInterface) EXPECT() *MockLikePostInterfaceMockRecorder {
	return m.recorder
}

// DeleteLikePost mocks base method.
func (m *MockLikePostInterface) DeleteLikePost(ctx context.Context, userID, postID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLikePost", ctx, userID, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLikePost indicates an expected call of DeleteLikePost.
func (mr *MockLikePostInterfaceMockRecorder) DeleteLikePost(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLikePost", reflect.TypeOf((*MockLikePostInterface)(nil).DeleteLikePost), ctx, userID, postID)
}

// GetPostLikeID mocks base method.
func (m *MockLikePostInterface) GetPostLikeID(ctx context.Context, userID, postID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostLikeID", ctx, userID, postID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostLikeID indicates an expected call of GetPostLikeID.
func (mr *MockLikePostInterfaceMockRecorder) GetPostLikeID(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostLikeID", reflect.TypeOf((*MockLikePostInterface)(nil).GetPostLikeID), ctx, userID, postID)
}

// GetPostLikes mocks base method.
func (m *MockLikePostInterface) GetPostLikes(ctx context.Context, postID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostLikes", ctx, postID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostLikes indicates an expected call of GetPostLikes.
func (mr *MockLikePostInterfaceMockRecorder) GetPostLikes(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostLikes", reflect.TypeOf((*MockLikePostInterface)(nil).GetPostLikes), ctx, postID)
}

// InsertLikePost mocks base method.
func (m *MockLikePostInterface) InsertLikePost(ctx context.Context, userID, postID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertLikePost", ctx, userID, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertLikePost indicates an expected call of InsertLikePost.
func (mr *MockLikePostInterfaceMockRecorder) InsertLikePost(ctx, userID, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertLikePost", reflect.TypeOf((*MockLikePostInterface)(nil).InsertLikePost), ctx, userID, postID)
}

// MockMediaInterface is a mock of MediaInterface interface.
type MockMediaInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMediaInterfaceMockRecorder
}

// MockMediaInterfaceMockRecorder is the mock recorder for MockMediaInterface.
type MockMediaInterfaceMockRecorder struct {
	mock *MockMediaInterface
}

// NewMockMediaInterface creates a new mock instance.
func NewMockMediaInterface(ctrl *gomock.Controller) *MockMediaInterface {
	mock := &MockMediaInterface{ctrl: ctrl}
	mock.recorder = &MockMediaInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaInterface) EXPECT() *MockMediaInterfaceMockRecorder {
	return m.recorder
}

// GetContentsByPost mocks base method.
func (m *MockMediaInterface) GetContentsByPost(ctx context.Context, postID string) ([]*models.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContentsByPost", ctx, postID)
	ret0, _ := ret[0].([]*models.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContentsByPost indicates an expected call of GetContentsByPost.
func (mr *MockMediaInterfaceMockRecorder) GetContentsByPost(ctx, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContentsByPost", reflect.TypeOf((*MockMediaInterface)(nil).GetContentsByPost), ctx, postID)
}
