// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Post ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Post ) UnmarshalJSON([]byte) error { return nil }
func ( Post ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Post ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Post *Post
