// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"

  pkg "github.com/go-park-mail-ru/2024_2_TeamOn_Patreon/internal/content/controller/models"
)

func main() {
  g := gen.NewGenerator("model_media_easyjson.go")
  g.SetPkg("models", "github.com/go-park-mail-ru/2024_2_TeamOn_Patreon/internal/content/controller/models")
  g.Add(pkg.EasyJSON_exporter_Media(nil))
  g.Add(pkg.EasyJSON_exporter_MediaResponse(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
