/*
 * PushART - Posts | API
 *
 * API для управления постами и лентой
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

//go:generate easyjson -all

//easyjson:json
type MediaUploadSuccessResponse struct {
	// Id загруженного медиа-контента
	MediaId string `json:"mediaId,omitempty"`
}
