// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( UpdateComment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UpdateComment ) UnmarshalJSON([]byte) error { return nil }
func ( UpdateComment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UpdateComment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UpdateComment *UpdateComment
