// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( MediaUploadSuccessResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* MediaUploadSuccessResponse ) UnmarshalJSON([]byte) error { return nil }
func ( MediaUploadSuccessResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MediaUploadSuccessResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MediaUploadSuccessResponse *MediaUploadSuccessResponse
