// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostId ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostId ) UnmarshalJSON([]byte) error { return nil }
func ( PostId ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostId ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostId *PostId
