// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( PostLikeBody ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PostLikeBody ) UnmarshalJSON([]byte) error { return nil }
func ( PostLikeBody ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PostLikeBody ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PostLikeBody *PostLikeBody
