// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( MediaUploadRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* MediaUploadRequest ) UnmarshalJSON([]byte) error { return nil }
func ( MediaUploadRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MediaUploadRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MediaUploadRequest *MediaUploadRequest
