// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( UpdatePost ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UpdatePost ) UnmarshalJSON([]byte) error { return nil }
func ( UpdatePost ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UpdatePost ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UpdatePost *UpdatePost
