// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AddComment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AddComment ) UnmarshalJSON([]byte) error { return nil }
func ( AddComment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AddComment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AddComment *AddComment
