// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC3e01bcbDecodeGithubComGoParkMailRu20242TeamOnPatreonInternalContentControllerModels(in *jlexer.Lexer, out *MediaGetSuccessResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "postId":
			out.PostId = string(in.String())
		case "mediaContent":
			if in.IsNull() {
				in.Skip()
				out.MediaContent = nil
			} else {
				in.Delim('[')
				if out.MediaContent == nil {
					if !in.IsDelim(']') {
						out.MediaContent = make([]MediaGetSuccessResponseMediaContent, 0, 1)
					} else {
						out.MediaContent = []MediaGetSuccessResponseMediaContent{}
					}
				} else {
					out.MediaContent = (out.MediaContent)[:0]
				}
				for !in.IsDelim(']') {
					var v1 MediaGetSuccessResponseMediaContent
					(v1).UnmarshalEasyJSON(in)
					out.MediaContent = append(out.MediaContent, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC3e01bcbEncodeGithubComGoParkMailRu20242TeamOnPatreonInternalContentControllerModels(out *jwriter.Writer, in MediaGetSuccessResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.PostId != "" {
		const prefix string = ",\"postId\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.PostId))
	}
	if len(in.MediaContent) != 0 {
		const prefix string = ",\"mediaContent\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v2, v3 := range in.MediaContent {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MediaGetSuccessResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC3e01bcbEncodeGithubComGoParkMailRu20242TeamOnPatreonInternalContentControllerModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MediaGetSuccessResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC3e01bcbEncodeGithubComGoParkMailRu20242TeamOnPatreonInternalContentControllerModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MediaGetSuccessResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC3e01bcbDecodeGithubComGoParkMailRu20242TeamOnPatreonInternalContentControllerModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MediaGetSuccessResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC3e01bcbDecodeGithubComGoParkMailRu20242TeamOnPatreonInternalContentControllerModels(l, v)
}
