// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( CustomSubscription ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CustomSubscription ) UnmarshalJSON([]byte) error { return nil }
func ( CustomSubscription ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CustomSubscription ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CustomSubscription *CustomSubscription

func ( SubscriptionLayer ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SubscriptionLayer ) UnmarshalJSON([]byte) error { return nil }
func ( SubscriptionLayer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SubscriptionLayer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SubscriptionLayer *SubscriptionLayer
