// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCf65193dDecodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(in *jlexer.Lexer, out *RatingModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "rating":
			out.Rating = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCf65193dEncodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(out *jwriter.Writer, in RatingModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Rating))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RatingModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCf65193dEncodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RatingModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCf65193dEncodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RatingModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCf65193dDecodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RatingModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCf65193dDecodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(l, v)
}
