// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson46c22afcDecodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(in *jlexer.Lexer, out *StatTable) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "theme":
			out.Theme = string(in.String())
		case "rating":
			out.Rating = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson46c22afcEncodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(out *jwriter.Writer, in StatTable) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"theme\":"
		out.RawString(prefix[1:])
		out.String(string(in.Theme))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.String(string(in.Rating))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatTable) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson46c22afcEncodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatTable) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson46c22afcEncodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatTable) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson46c22afcDecodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatTable) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson46c22afcDecodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(l, v)
}
