// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson21155660DecodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(in *jlexer.Lexer, out *ModelCanShow) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "isCanShow":
			out.CanAsk = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson21155660EncodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(out *jwriter.Writer, in ModelCanShow) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"isCanShow\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.CanAsk))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ModelCanShow) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson21155660EncodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ModelCanShow) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson21155660EncodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ModelCanShow) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson21155660DecodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ModelCanShow) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson21155660DecodeGithubComGoParkMailRu20242TeamOnPatreonInternalCsatControllerModels(l, v)
}
