// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  postgresql

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( CustomSubscriptionRepository ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CustomSubscriptionRepository ) UnmarshalJSON([]byte) error { return nil }
func ( CustomSubscriptionRepository ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CustomSubscriptionRepository ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CustomSubscriptionRepository *CustomSubscriptionRepository
