// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Comment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Comment ) UnmarshalJSON([]byte) error { return nil }
func ( Comment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Comment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Comment *Comment
