// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Media ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Media ) UnmarshalJSON([]byte) error { return nil }
func ( Media ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Media ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Media *Media
