// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  repositories

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Postgres ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Postgres ) UnmarshalJSON([]byte) error { return nil }
func ( Postgres ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Postgres ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Postgres *Postgres
