// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  controller

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Handler ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Handler ) UnmarshalJSON([]byte) error { return nil }
func ( Handler ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Handler ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Handler *Handler
